classdef UICheckbox < guiser.component.UIElement & ...
                      guiser.component.mixin.UIVisible & ...
                      guiser.component.mixin.UIVisualComponent & ...
                      guiser.component.mixin.UITextComponent & ...
                      guiser.component.mixin.UIInteractiveComponent & ...
                      guiser.component.mixin.UITFValue & ...
                      guiser.component.mixin.UIValueChangedFcn & ...
                      guiser.component.mixin.UIText
    % UICHECKBOX Describes a checkbox UI component.
    %
    % This class uses multiple inheritance to compose all necessary features
    % from the elemental, visual, text, interactive, and value mixin classes.

end