classdef UIEditField < guiser.component.UIElement & ...
                       guiser.component.mixin.UIVisualComponent & ...
                       guiser.component.mixin.UIUnits & ...
                       guiser.component.mixin.UIBackgroundColor & ...                                          
                       guiser.component.mixin.UITextComponent & ...
                       guiser.component.mixin.UIInteractiveComponent & ...
                       guiser.component.mixin.UIValue & ...
                       guiser.component.mixin.UIValueChangedFcn & ...
                       guiser.component.mixin.UIValueChangingFcn &...
                       guiser.component.mixin.UIHorizontalAlignment &...
                       guiser.component.mixin.UIPlaceholder
    % UIEDITFIELD Describes an editable, single-line text field.

end