classdef UILabel < guiser.component.UIElement & ...
                   guiser.component.mixin.UIVisualComponent & ...
                   guiser.component.mixin.UITextComponent &...
                   guiser.component.mixin.UIHorizontalAlignment & ...
                   guiser.component.mixin.UIVerticalAlignment & ...
                   guiser.component.mixin.UIText

    % UILABEL Describes a static text label UI component.

end