classdef UIPanel < guiser.component.mixin.UIContainer & ...
                   guiser.component.mixin.UIVisualComponent & ...
                   guiser.component.mixin.UIUnits & ...                   
                   guiser.component.mixin.UIBackgroundColor & ...                                      
                   guiser.component.mixin.UITextComponent & ...
                   guiser.component.mixin.UITitle & ...
                   guiser.component.mixin.UIBorderType & ...
                   guiser.component.UIElement

    % UIPANEL Describes a panel container component.
    
end