classdef UITab < guiser.component.mixin.UIContainer & ...
                 guiser.component.mixin.UIVisualComponent & ...
                 guiser.component.mixin.UIBackgroundColor & ...                                    
                 guiser.component.mixin.UITextComponent & ...
                 guiser.component.mixin.UITitle & ...
                 guiser.component.UIElement 
    % UITAB Describes a single tab within a tab group.
    
    properties
    end

end