classdef UITextArea < guiser.component.UIElement & ...
                      guiser.component.mixin.UIVisible & ...
                      guiser.component.mixin.UIVisualComponent & ...
                      guiser.component.mixin.UIBackgroundColor & ...  
                      guiser.component.mixin.UIUnits & ...                      
                      guiser.component.mixin.UITextComponent & ...
                      guiser.component.mixin.UIInteractiveComponent & ...
                      guiser.component.mixin.UIValue & ...
                      guiser.component.mixin.UIValueChangedFcn & ...
                      guiser.component.mixin.UIValueChangingFcn & ...
                      guiser.component.mixin.UIPlaceholder & ...
                      guiser.component.mixin.UIWordWrap
    % UITEXTAREA Describes an editable, multi-line text area.
    
    methods
        function obj = UITextArea()
            % Override the default WordWrap from UITextComponent for this class
            obj.WordWrap = 'on';
        end
    end
    
end