# General GitHub Repository Settings
repository:
  license: CC-BY-NC-4.0      # Select a license from the options below
  # License Options:
  # - None
  # - AGPL-3.0 
  # - Apache-2.0 
  # - BSD-2-Clause 
  # - BSD-3-Clause 
  # - EPL-1.0 
  # - GPL-2.0 
  # - GPL-3.0 
  # - LGPL-2.1 
  # - LGPL-3.0 
  # - MIT 
  # - MPL-2.0 
  # - Unlicense 

# MATLAB Toolbox Settings
matlab_toolbox:
  namespace_name: guiser                         # A unique namespace for your toolbox
  toolbox_name: guiser                           # Name of the MATLAB toolbox                  
  author_name: Waltham Data Science                     
  author_email: info@walthamdatascience.com         
  author_company: Waltham Data Science                     # Author's company or organization
  toolbox_summary: A GUI package where most components are serialized for easier cross-platform development
  toolbox_description: |
    GUISER - GUI / Serialized toolbox. Allows one to specify GUI elements and links
    to data structures with JSON. Only a few actions must be specified by code, allowing
    easier cross-platform development.
